#pragma once

#define USBD_LANGID_STRING				1033
#define USBD_VID						0x1209
#define USBD_PID_FS						0x9450
#define USBD_MANUFACTURER_STRING		"xil.se"
#define USBD_PRODUCT_STRING_FS			"XilDebug"
#define USBD_SERIALNUMBER_STRING_FS		"123456789ABC"
#define USBD_CONFIGURATION_STRING_FS	"CDC Config"
#define USBD_INTERFACE_STRING_FS		"CDC Interface"

#define USB_SIZ_BOS_DESC				0x0C
